### PR TITLE
Respect user CXXFLAGS

### PR DESCRIPTION
**Pull request by zauguin**

### CODE REVIEW

**Comment by jll63** [comment]
Hi Marcel,

Thanks. Merged.

Also pleased to see that there are people using this thing? ;)

Jean-Louis

**Comment by zauguin** [comment]
I wanted to use the visitor pattern for the LLVM kaleidoscope tutorial and decided that I really don't like visaitors and there has to be a better way.  ;)

**Comment by jll63** [comment]
Interesting. Do you plan to publish this? I would be very interested to see it, and it may be a good example application of yomm11.

**Comment by zauguin** [comment]
That wasn't my original plan, but I may publish it after some cleanup.

**Pull request merged**
